services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py && python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "celery -A configs worker -l info"
  

#  db:
#    image: mysql:8
#    env_file:
#      - .env
#    volumes:
#      - ./mysql:/var/lib/mysql
#    ports:
#      - "3307:3306"
#    restart: on-failure
