# Generated by Django 5.1.6 on 2025-02-18 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='name',
            field=models.CharField(error_messages={'Detail': 'Name is not valid'}, max_length=25, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')]),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='surname',
            field=models.CharField(error_messages={'Detail': 'Surname is not valid'}, max_length=25, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')]),
        ),
    ]
