# Generated by Django 5.1.6 on 2025-02-24 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, error_messages={'Details': 'Name is not valid'}, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')])),
                ('surname', models.CharField(blank=True, error_messages={'Details': 'Surname is not valid'}, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, error_messages={'Details': 'Phone number is not valid'}, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?380\\d{9}$')])),
                ('age', models.IntegerField(blank=True, error_messages={'Details': "Available year's range: 16 - 100"}, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)])),
                ('course', models.CharField(blank=True, choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=4, null=True)),
                ('course_format', models.CharField(blank=True, choices=[('static', 'Static'), ('online', 'Online')], max_length=6, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], max_length=9, null=True)),
                ('status', models.CharField(blank=True, choices=[('In work', 'In Work'), ('Dubbing', 'Dubbing'), ('New', 'New'), ('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=8, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('alreadyPaid', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('id',),
            },
        ),
    ]
