# Generated by Django 5.2 on 2025-05-12 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersmodel_group_ordersmodel_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='name',
            field=models.CharField(blank=True, error_messages={'Details': 'Name is not valid'}, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex="^[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ']{1,29}$")]),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='surname',
            field=models.CharField(blank=True, error_messages={'Details': 'Surname is not valid'}, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex="^[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ']{1,29}$")]),
        ),
    ]
