# Generated by Django 5.2 on 2025-05-14 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersmodel_group_ordersmodel_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator("^[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ']{1,29}$", 'Must start with a capital letter and contain only the letters')]),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?380\\d{9}$', 'The number format must be as follows: +380501234567, 380501234567')]),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='surname',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator("^[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ']{1,29}$", 'Must start with a capital letter and contain only the letters')]),
        ),
    ]
