# Generated by Django 5.2 on 2025-05-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_groupmodel_commentsmodel_ordersmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_group', to='orders.groupmodel'),
        ),
    ]
