# Generated by Django 5.1.6 on 2025-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('course', models.CharField(blank=True, choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=4, null=True)),
                ('course_format', models.CharField(blank=True, choices=[('static', 'Static'), ('online', 'Online')], max_length=6, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], max_length=9, null=True)),
                ('status', models.CharField(blank=True, choices=[('In work', 'In Work'), ('Dubbing', 'Dubbing'), ('New', 'New'), ('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=8, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('alreadyPaid', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'student_application',
                'ordering': ('id',),
            },
        ),
    ]
